**Reannotating the Steinmetz data** <br>
<br>
I need to reannotate the data so that I can identify which channels are best to locate SWRs from using the de la Prida et al., (2022) CNN SWR detector.  It will also allow me to make claims about layer specific effects in cortex.  I am going to be following this tutorial [here](https://github.com/datajoint/workflow-array-ephys/blob/main/notebooks/08-electrode-localization.ipynb).  Note that in order to run the notebook you will need to set up the electorphys datajoint workflow which is explained in [this notebook](https://github.com/datajoint/workflow-array-ephys/blob/main/notebooks/01-configure.ipynb).  Youtube tutorial by the author is [here](https://www.youtube.com/watch?v=YRXokFHkLGg).  The annotation files are located [here](http://download.alleninstitute.org/informatics-archive/current-release/mouse_ccf/annotation/ccf_2017/), I am using the 25$\mu$_m_ CCF annotation file. This is the Allen institute [tutorial for using reference spaces](https://allensdk.readthedocs.io/en/latest/_static/examples/nb/reference_space.html) which should be useful there is also one which uses the connectivity data [here](https://github.com/AllenInstitute/CCF_Tutorial/blob/main/CCF_Tutorial.ipynb).

In [34]:
import numpy as np

In [18]:
import nrrd

In [19]:
annotation_25, header = nrrd.read('annotation_25.nrrd')

In [27]:
test_cord = [6936.2,1931.7,4497.7] # should be in CA1
[int(x/25) for x in test_cord]

[277, 77, 179]

In [24]:
annotation_25[693, 193,450]

IndexError: index 693 is out of bounds for axis 0 with size 528

In [25]:
header

OrderedDict([('type', 'unsigned int'),
             ('dimension', 3),
             ('space', 'left-posterior-superior'),
             ('sizes', array([528, 320, 456])),
             ('space directions',
              array([[25.,  0.,  0.],
                     [ 0., 25.,  0.],
                     [ 0.,  0., 25.]])),
             ('kinds', ['domain', 'domain', 'domain']),
             ('endian', 'little'),
             ('encoding', 'gzip'),
             ('space origin', array([0., 0., 0.]))])

In [28]:
annotation_25[277, 77, 179]

382

In [30]:
annotation_10, header = nrrd.read('annotation_10.nrrd')

In [32]:
test_cord = [6936.2,1931.7,4497.7] # should be in CA1
test_cord_10 = [int(x/10) for x in test_cord]
annotation_10[test_cord_10[0], test_cord_10[1], test_cord_10[2]]

382

In [37]:
result = np.where(annotation_10 == 382) # this is the structure Id for CA1

In [38]:
result

(array([631, 631, 631, ..., 900, 900, 900]),
 array([193, 193, 193, ..., 426, 426, 426]),
 array([470, 471, 668, ..., 156, 983, 984]))

In [5]:
result = np.where(annotation_10 == 407) # this is the structure Id for CA1 pyramidal layer

In [5]:
# change to the upper level folder to detect dj_local_conf.json
import os
if os.path.basename(os.getcwd()) == "notebooks":
    os.chdir("..")

In [6]:
# We'll be working with long tables, so we'll make visualization easier with a limit
import datajoint as dj
dj.config["display.limit"] = 10

In [7]:
from workflow_array_ephys.localization import coordinate_framework as ccf

ModuleNotFoundError: No module named 'workflow_array_ephys'